### ISSUE TITLE
delete it! :-)

### ISSUE THREAD

**Issue by cykonetic** [TheDMSGroup/mautic-contact-source#6]
https://github.com/TheDMSGroup/mautic-contact-source/blob/1b8589146061d4ad09b762f64fd77711345cb9e7/Model/Attribution.php#L125

The Lead entity will check for that automatically...let them handle their own BC?

https://github.com/mautic/mautic/blob/aacc5a9ff954dd484e6a4015e8eba6e1e41fd50b/app/bundles/LeadBundle/Entity/Lead.php#L1539

**Comment by heathdutton** [comment]
It does not update the date to the latest attribution. It only establishes one if the field is empty and an attribution value (other than 0/null) exists.

So if I delete this, then attribution_date will always only be the moment of the initial ingestion...
Is that ok?
